#!/bin/bash


module purge
module load profile/advanced
module load autoload intelmpi/5.0.1--binary netcdf/4.1.3--intel--cs-xe-2015--binary
module load autoload python/2.7.9 numpy/1.9.2--python--2.7.9 matplotlib/1.4.3--python--2.7.9 scipy/0.15.1--python--2.7.9
source /gpfs/work/OGS16_PRACE_P/COPERNICUS/py_env_2.7.9/bin/activate
PYTHONPATH=$PYTHONPATH:/pico/scratch/userexternal/gbolzon0/bit.sea

export OPA_HOME=FDA_all2015_newstd_3days


#     TMP_DIR=$CINECA_SCRATCH/$OPA_HOME/wrkdir/POSTPROC/output/AVE_FREQ_1/TMP
     TMP_DIR=$CINECA_SCRATCH/$OPA_HOME/wrkdir/POSTPROC/output/AVE_FREQ_1/TMP/
     BASEDIR=$CINECA_SCRATCH/$OPA_HOME/wrkdir/float_preproc/PROFILATORE_WEEKLY_LOV_OGSTM/
      OPADIR=$CINECA_SCRATCH/$OPA_HOME/wrkdir/float_preproc/
    DEST_DIR=$CINECA_SCRATCH/$OPA_HOME/wrkdir/MODEL/

  export MASKFILE=/pico/home/usera07ogs/a07ogs00/OPA/V2C/etc/static-data/MED1672_cut/MASK/meshmask.nc

cd  $OPADIR

#/bin/rm daTimes alldates

#python genUserDateList_interval.py >> alldates
for DATE in `cat alldates`
do
  echo ${DATE:3}
  sed -e 's/\-//g' $DATE

#  python float_extractor.py       -t ${DATE}  -i $TMP_DIR -b $BASEDIR  -d $OPADIR
#  if [ $? -ne 0 ] ; then exit 1 ; fi

#  python CheckFloatperDate.py -t ${DATE}  -i $TMP_DIR -b $BASEDIR >> daTimes
#  if [ $? -ne 0 ] ; then exit 1 ; fi

done
#cp daTimes $DEST_DIR
